/*
CREATED		4/17/2023
MODIFIED		4/17/2023
PROJECT		
MODEL		
COMPANY		
AUTHOR		
VERSION		
DATABASE		MYSQL 5 
*/

USE master
DROP DATABASE IF EXISTS KaintoMusic
CREATE DATABASE KaintoMusic
USE KaintoMusic 

CREATE TABLE USERS (
	USERID INT NOT NULL,
	MONEY INT,
	PRIMARY KEY (USERID)
)
CREATE TABLE ACCOUNT (
	USERID INT NOT NULL,
	USERNAME CHAR(20) NOT NULL,
	PASSWORD CHAR(20),
	ROLE INT,
	PRIMARY KEY (USERNAME),
	FOREIGN KEY (USERID) REFERENCES USERS(USERID)
)
CREATE TABLE MUSIC (
	MUSICID INT NOT NULL,
	NAME NVARCHAR(20),
	ARTIST NVARCHAR(20),
	ALBUM NVARCHAR(40),
	PRICE INT,
	BUYED INT,
	PRIMARY KEY (MUSICID)
)
CREATE TABLE VIDEO (
	VIDEOID INT NOT NULL,
	NAME NVARCHAR(20),
	ARTIST NVARCHAR(20),
	PRIMARY KEY (VIDEOID)
)
CREATE TABLE MUSICHAVE (
	USERID INT NOT NULL,
	MUSICID INT NOT NULL,
	FOREIGN KEY (USERID) REFERENCES USERS(USERID),
	FOREIGN KEY (MUSICID) REFERENCES MUSIC(MUSICID)
)
CREATE TABLE VIDEOHAVE (
	USERID INT NOT NULL,
	VIDEOID INT NOT NULL,
	FOREIGN KEY (USERID) REFERENCES USERS(USERID),
	FOREIGN KEY (VIDEOID) REFERENCES VIDEO(VIDEOID)
)

SELECT * FROM USERS
SELECT * FROM ACCOUNT
SELECT * FROM MUSIC
SELECT * FROM VIDEO
SELECT * FROM MUSICHAVE
SELECT * FROM VIDEOHAVE

INSERT INTO USERS VALUES (0,0),
						 (1,0)

INSERT INTO ACCOUNT VALUES (0,'GuenKainto','guenkainto',0),
						   (1,'user1','user1',1)
/*
INSERT INTO MUSIC VALUES ()

INSERT INTO VIDEO VALUES ()

INSERT INTO MUSICHAVE VALUES ()

INSERT INTO VIDEOHAVE VALUESS ()
*/